### ISSUE TITLE
pun failure

### ISSUE THREAD

**Issue by CharlesWall** [austinkelleher/dynograte#4]
![0143](https://cloud.githubusercontent.com/assets/1440999/18325023/616e3068-750d-11e6-8bab-bde181fdd8b5.jpg)

**Comment by austinkelleher** [comment]
![image](https://cloud.githubusercontent.com/assets/3771924/18325204/37ec20aa-750e-11e6-9f1d-8a62eba68872.png)

**Comment by CharlesWall** [comment]
dyno-ok...
